export const servicesData = [
    {
      category: "Standard Maintenance Services",
      services: [
        "Factory Scheduled Maintenance",
        "30/60/90/120 Mile Services",
        "Computer Diagnostics",
        "Oil Changes",
        "Tune Ups",
        "Filter Replacements",
        "Safety & Emissions Inspections",
        "Windshield Wiper Blades",
        "Fluid Services",
        "Trip Inspections",
        "Maintenance Inspections",
        "Check Engine Light Diagnostics & Repair",
        "Brake Repair & ABS Repair",
        "Shocks & Struts Repair",
        "Chassis & Suspension Repair",
        "Suspension & Steering Repair",
      ],
    },
    {
      category: "Engine Services",
      services: [
        "Engine Repair",
        "Engine Replacement",
        "Engine Performance Check",
        "Belt Replacement",
        "Hose Replacement",
        "Cooling System Repair",
        "Radiator Repair & Replacement",
        "Water Pump Repair & Replacement",
        "Drivability Diagnostics & Repair",
        "Fuel Injection Repair & Service",
        "Fuel System Repair & Maintenance",
        "Ignition System Repair & Maintenance",
      ],
    },
    {
      category: "Heating & Air Conditioner Repair",
      services: [
        "Heating & Cooling System Diagnostics",
        "Auto Air Conditioning Repair & Service",
        "Heating System Repair & Service",
        "Belt Repair & Replacement",
        "Compressor Repair & Replacement",
        "Evaporator Repair & Replacement",
      ],
    },
    {
      category: "Auto Electrical Services",
      services: [
        "Electrical System Diagnostics & Repair",
        "Alternator Repair & Replacement",
        "Starter Repair & Replacement",
        "Windshield Wiper Repair",
        "Power Lock Repair",
        "Power Antenna Repair",
        "Power Steering Repair",
        "Power Window Repair",
        "Power Accessory Repair",
        "Light Repair & Bulb Replacements",
      ],
    },
    {
      category: "Exhaust Services",
      services: [
        "Exhaust Repair & Replacement",
        "Muffler Repair & Replacement",
        "Tailpipe Repair & Replacement",
      ],
    },
  ];