export const servicesData = [
  {
    category: "standard_maintenance_services",
    services: [
      "factory_scheduled_maintenance",
      "30/60/90/120_mile_services",
      "computer_diagnostics",
      "oil_changes",
      "tune_ups",
      "filter_replacements",
      "safety_emissions_inspections",
      "windshield_wiper_blades",
      "fluid_services",
      "trip_inspections",
      "maintenance_inspections",
      "check_engine_light_diagnostics_repair",
      "brake_repair_abs_repair",
      "shocks_struts_repair",
      "chassis_suspension_repair",
      "suspension_steering_repair",
    ],
  },
  {
    category: "engine_services",
    services: [
      "engine_repair",
      "engine_replacement",
      "engine_performance_check",
      "belt_replacement",
      "hose_replacement",
      "cooling_system_repair",
      "radiator_repair_replacement",
      "water_pump_repair_replacement",
      "drivability_diagnostics_repair",
      "fuel_injection_repair_service",
      "fuel_system_repair_maintenance",
      "ignition_system_repair_maintenance",
    ],
  },
  {
    category: "heating_air_conditioner_repair",
    services: [
      "heating_cooling_system_diagnostics",
      "auto_air_conditioning_repair_service",
      "heating_system_repair_service",
      "belt_repair_replacement",
      "compressor_repair_replacement",
      "evaporator_repair_replacement",
    ],
  },
  {
    category: "auto_electrical_services",
    services: [
      "electrical_system_diagnostics_repair",
      "alternator_repair_replacement",
      "starter_repair_replacement",
      "windshield_wiper_repair",
      "power_lock_repair",
      "power_antenna_repair",
      "power_steering_repair",
      "power_window_repair",
      "power_accessory_repair",
      "light_repair_bulb_replacements",
    ],
  },
  {
    category: "exhaust_services",
    services: [
      "exhaust_repair_replacement",
      "muffler_repair_replacement",
      "tailpipe_repair_replacement",
    ],
  },
];
